steps:
  # Build the container image using Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/trade-journal-backend:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/trade-journal-backend:latest', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/trade-journal-backend:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'trade-journal-backend'
      - '--image=gcr.io/$PROJECT_ID/trade-journal-backend:latest'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--clear-base-image'

images:
  - 'gcr.io/$PROJECT_ID/trade-journal-backend:latest'

timeout: 1200s
